export { articlesDetailsReducer } from "./model/slice/artliDetailsSlice"
export { default as ArticleTypeTabs } from ".//ui/ArticleTypeTabs/ArticleTypeTabs"
export { default as ArticleSortSelector } from "./ui/ArticleSortSelector/ArticleSortSelector"
export { default as ArticleViewSelector } from "./ui/ArticleViewSelector/ArticleViewSelector"
export { getArticleDetailsData } from "./model/selectors/articleDetails"
export { fetchArticleById } from "./model/services/fetchArticleById/fetchArticleById"
export type { Article } from "./model/types/article"
export type { ArticleDetailsSchema } from "./model/types/articleDetailsSchema"
export { default as ArticleDetails } from "./ui/ArticleDetails/ArticleDetails"
export {ArticleType, ArticleSortField, ArticleView, ArticleBlockType} from "./model/const/const"
