export {default as ArticleViewSelector} from "entitie/Article/ui/ArticleViewSelector/ArticleViewSelector"
export {ArticleView} from "./model/types/article"
export {getArticleDetailsData} from "./model/selectors/articleDetails"
export {fetchArticleById} from "./model/services/fetchArticleById/fetchArticleById"
export type { Article } from "./model/types/article"
export type { ArticleDetailsSchema } from "./model/types/articleDetailsSchema"
export { default as ArticleDetails } from "./ui/ArticleDetails/ArticleDetails"
